### ISSUE TITLE
__load__.zeek is missing in v1.0.0

### ISSUE THREAD

**Issue by jloehel** [pgaulon/bro-notice-slack#1]
The installation via zkg seems to work but nothing is copied into the plugin/script folder. I guess because of the missing load instructions in v1.0.0:

```
Failed to load "zeek/pgaulon/zeek-notice-slack": no __load__.zeek within package script_dir and no plugin included
```

Could you please release a new version. :-)

**Comment by pgaulon** [comment]
Hello!
Sorry for that, I created a [new release](https://github.com/pgaulon/zeek-notice-slack/releases/tag/1.0.1).
