### ISSUE TITLE
Can't find base/utils/json

### ISSUE THREAD

**Issue by jloehel** [pgaulon/bro-notice-slack#2]
Hi,

json.seek is not longer available in base/utils

> 
>   to_json is now a bif, no longer a script. Loading base/utils/json.zeek is no
>   longer necessary and has been deprecated. to_json should yield much better, always
>   valid json. There are some small differences in output; unnecessary spaces are removed
>   and port values are rendered differently, now including the port and the protocol.

**Comment by pgaulon** [comment]
Hello!

Thanks for the heads up, I removed the load line:
https://github.com/pgaulon/zeek-notice-slack/commit/54dde1b924e630d7af943d91d807019bfa0d2577
