### ISSUE TITLE
Error when deploying in Zeek 6.0.0

### ISSUE THREAD

**Issue by canarieids** [pgaulon/bro-notice-slack#3]
Hello,
Thank you for developing this Zeek-Slack integration plugin.  We have been using this in our environment for some time now and have enjoyed its notification enhancements.

However, after upgrading a test machine to Zeek Version 6.0.0 , we now receive the following error regarding this Slack plugin:

"
error in /opt/zeek/share/zeek/site/zeek-notice-slack/./notice_slack.zeek, lines 45-49: Notice::request is used inside "when" statement but not captured (when (Notice::result = ActiveHTTP::request(Notice::request)) { if (Notice::result$code != 200) Reporter::warning(fmt(Slack notice received an error status code: %d, Notice::result$code))})
"

Would you have any recommendations on how we can rectify this issue?

**Comment by pgaulon** [comment]
Thanks you @canarieids for the heads up, all set with release 1.0.2. Thanks as well @ottobackwards for the [PR](https://github.com/pgaulon/zeek-notice-slack/pull/4), much appreciated!
